// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: project.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectParticipant = `-- name: AddProjectParticipant :one
INSERT INTO project_participants (
    project_id,
    user_id,
    role
) VALUES (
    $1, $2, $3
) RETURNING project_id, user_id, role, joined_at
`

type AddProjectParticipantParams struct {
	ProjectID int64  `json:"project_id"`
	UserID    int64  `json:"user_id"`
	Role      string `json:"role"`
}

func (q *Queries) AddProjectParticipant(ctx context.Context, arg AddProjectParticipantParams) (ProjectParticipant, error) {
	row := q.db.QueryRow(ctx, addProjectParticipant, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectParticipant
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    title,
    description,
    start_date,
    end_date,
    created_by
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, title, description, start_date, end_date, created_by
`

type CreateProjectParams struct {
	Title       string      `json:"title"`
	Description string      `json:"description"`
	StartDate   time.Time   `json:"start_date"`
	EndDate     time.Time   `json:"end_date"`
	CreatedBy   pgtype.Int4 `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, title, description, start_date, end_date, created_by FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
	)
	return i, err
}

const listProjectParticipants = `-- name: ListProjectParticipants :many
SELECT e.id, e.name, e.email, e.role
FROM employees e
JOIN project_participants pp ON e.id = pp.user_id
WHERE pp.project_id = $1
`

func (q *Queries) ListProjectParticipants(ctx context.Context, projectID int64) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listProjectParticipants, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, description, start_date, end_date, created_by FROM projects
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectParticipant = `-- name: RemoveProjectParticipant :exec
DELETE FROM project_participants
WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectParticipantParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) RemoveProjectParticipant(ctx context.Context, arg RemoveProjectParticipantParams) error {
	_, err := q.db.Exec(ctx, removeProjectParticipant, arg.ProjectID, arg.UserID)
	return err
}

const updateParticipantRole = `-- name: UpdateParticipantRole :one
UPDATE project_participants
SET role = $3
WHERE project_id = $1 AND user_id = $2
RETURNING project_id, user_id, role, joined_at
`

type UpdateParticipantRoleParams struct {
	ProjectID int64  `json:"project_id"`
	UserID    int64  `json:"user_id"`
	Role      string `json:"role"`
}

func (q *Queries) UpdateParticipantRole(ctx context.Context, arg UpdateParticipantRoleParams) (ProjectParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantRole, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectParticipant
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
    SET title = $2,
    end_date = $3
WHERE id = $1
RETURNING id, title, description, start_date, end_date, created_by
`

type UpdateProjectParams struct {
	ID      int64     `json:"id"`
	Title   string    `json:"title"`
	EndDate time.Time `json:"end_date"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Title, arg.EndDate)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
	)
	return i, err
}
