// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteEmployee(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteTask(ctx context.Context, id int64) error
	GetEmployee(ctx context.Context, id int64) (Employee, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	ListEmployeeHistory(ctx context.Context, changedBy pgtype.Int4) ([]History, error)
	ListEmployeeTasks(ctx context.Context, assignedTo pgtype.Int4) ([]Task, error)
	ListEmployees(ctx context.Context) ([]Employee, error)
	ListProjectTasks(ctx context.Context, projectID pgtype.Int4) ([]Task, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListTaskHistory(ctx context.Context, taskID pgtype.Int4) ([]History, error)
	ListTasks(ctx context.Context) ([]Task, error)
	UpdateEmployeeFirstName(ctx context.Context, arg UpdateEmployeeFirstNameParams) (Employee, error)
	UpdateEmployeeLastName(ctx context.Context, arg UpdateEmployeeLastNameParams) (Employee, error)
	UpdateEmployeePassword(ctx context.Context, arg UpdateEmployeePasswordParams) (Employee, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTaskDeadline(ctx context.Context, arg UpdateTaskDeadlineParams) (Task, error)
	UpdateTaskDescription(ctx context.Context, arg UpdateTaskDescriptionParams) (Task, error)
	UpdateTaskPriority(ctx context.Context, arg UpdateTaskPriorityParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateTaskTitle(ctx context.Context, arg UpdateTaskTitleParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
