// Code generated by sqlc. DO NOT EDIT.
// source: history.sql

package db

import (
	"context"
	"database/sql"
)

const createHistory = `-- name: CreateHistory :one
INSERT INTO histories (
    task_id,
    changed_by,
    old_status,
    new_status
)
VALUES (
    $1, $2, $3, $4
)
RETURNING id, task_id, changed_by, change_at, old_status, new_status
`

type CreateHistoryParams struct {
	TaskID    sql.NullInt32 `json:"task_id"`
	ChangedBy sql.NullInt32 `json:"changed_by"`
	OldStatus string        `json:"old_status"`
	NewStatus string        `json:"new_status"`
}

func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error) {
	row := q.db.QueryRowContext(ctx, createHistory,
		arg.TaskID,
		arg.ChangedBy,
		arg.OldStatus,
		arg.NewStatus,
	)
	var i History
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ChangedBy,
		&i.ChangeAt,
		&i.OldStatus,
		&i.NewStatus,
	)
	return i, err
}

const listEmployeeHistory = `-- name: ListEmployeeHistory :many
SELECT id, task_id, changed_by, change_at, old_status, new_status FROM histories
WHERE changed_by = $1
`

func (q *Queries) ListEmployeeHistory(ctx context.Context, changedBy sql.NullInt32) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeeHistory, changedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ChangedBy,
			&i.ChangeAt,
			&i.OldStatus,
			&i.NewStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskHistory = `-- name: ListTaskHistory :many
SELECT id, task_id, changed_by, change_at, old_status, new_status FROM histories
WHERE task_id = $1
`

func (q *Queries) ListTaskHistory(ctx context.Context, taskID sql.NullInt32) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listTaskHistory, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ChangedBy,
			&i.ChangeAt,
			&i.OldStatus,
			&i.NewStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
