// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Employee struct {
	ID           int64  `json:"id"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

type History struct {
	ID        int64         `json:"id"`
	TaskID    sql.NullInt32 `json:"task_id"`
	ChangedBy sql.NullInt32 `json:"changed_by"`
	ChangeAt  time.Time     `json:"change_at"`
	OldStatus string        `json:"old_status"`
	NewStatus string        `json:"new_status"`
}

type Project struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	StartDate   time.Time     `json:"start_date"`
	EndDate     time.Time     `json:"end_date"`
	CreatedBy   sql.NullInt32 `json:"created_by"`
}

type Task struct {
	ID          int64         `json:"id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	CreatedAt   time.Time     `json:"created_at"`
	DueTo       time.Time     `json:"due_to"`
	Status      string        `json:"status"`
	Priority    string        `json:"priority"`
	ProjectID   sql.NullInt32 `json:"project_id"`
	AssignedTo  sql.NullInt32 `json:"assigned_to"`
}
