// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteEmployee(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteTask(ctx context.Context, id int64) error
	GetEmployee(ctx context.Context, id int64) (Employee, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	ListEmployeeHistory(ctx context.Context, changedBy pgtype.Int4) ([]History, error)
	ListEmployeeTasks(ctx context.Context, assignedTo pgtype.Int4) ([]Task, error)
	ListEmployees(ctx context.Context) ([]Employee, error)
	ListProjectTasks(ctx context.Context, projectID pgtype.Int4) ([]Task, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListTaskHistory(ctx context.Context, taskID pgtype.Int4) ([]History, error)
	ListTasks(ctx context.Context) ([]Task, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
